# yaml-language-server: $schema=https://json-schema.axonivy.com/14.0-dev/config/roles.json
Roles:
  - Id: PizzaCustomer
  - Id: PizzaWorker
    Members:
      - PizzaCustomer
      - PizzaChef
      - DeliveryBoy
  - Id: Clerk
    Parent: PizzaWorker
  - Id: PizzaChef
    Parent: PizzaWorker
  - Id: DeliveryBoy
    Parent: PizzaWorker
  - Id: Admin
