# yaml-language-server: $schema=https://json-schema.axonivy.com/15.1/config/variables.json
Variables:
  config:
    # The name of the JPA that you are using. You can set up a JPA in the persistence.yaml file. Its needed for every repository class.
    jpaName: PizzaProcessJPA
